In [1]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [2]:
#1.Vector as a row
vector_row=np.array([1,2,3,4]) 
vector_row

array([1, 2, 3, 4])

In [3]:
#2.Vector as a column
vector_column=np.array([[1],
                       [2],
                       [3]])
vector_column

array([[1],
       [2],
       [3]])

In [4]:
#matrix
matrix=np.array([[1,2],[3,4]])
matrix

array([[1, 2],
       [3, 4]])

In [5]:
matrix_object=np.mat([[1,2],[3,4],[5,6]])
matrix_object

matrix([[1, 2],
        [3, 4],
        [5, 6]])

In [6]:
#sparse matrix
from scipy import sparse
matrix_object=np.mat([[0,0],[0,4],[5,0]])
sparse_matrix=sparse.csr_matrix(matrix_object)
print(sparse_matrix)

  (1, 1)	4
  (2, 0)	5


In [7]:
#preallocation of numpy(nd array)
vector=np.zeros(shape=(2,2))
vector

array([[0., 0.],
       [0., 0.]])

In [8]:
vector=np.full(shape=(3,4),fill_value=1)
vector

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [9]:
#slicing
vector=[0,12,3,4,5,6]
print(vector[::-2])

[6, 4, 12]


In [10]:
## matrix selection
matrix=np.mat([[1,2,3],[4,5,7],[8,9,10]])
print(matrix[:2,1:3])

[[2 3]
 [5 7]]


In [11]:
#transpose Matrix
matrix.T

matrix([[ 1,  4,  8],
        [ 2,  5,  9],
        [ 3,  7, 10]])

In [12]:
matrix.reshape(1,9)

matrix([[ 1,  2,  3,  4,  5,  7,  8,  9, 10]])