In [1]:
import pandas as pd
import numpy as np


In [2]:
feature=np.array([['mumbai'],
                  ['pune'],
                  ['delhi'],
                  ['kolhapur']])

In [3]:
from sklearn.preprocessing import LabelBinarizer,MultiLabelBinarizer

In [4]:
one_hot=LabelBinarizer()

In [5]:
one_hot.fit_transform(feature)

array([[0, 0, 1, 0],
       [0, 0, 0, 1],
       [1, 0, 0, 0],
       [0, 1, 0, 0]])

In [6]:
one_hot.classes_

array(['delhi', 'kolhapur', 'mumbai', 'pune'], dtype='<U8')

In [7]:
# one_hot.inverse_transform(one_hot.fit_transform(feature))

In [8]:
pd.get_dummies(feature[:,0])

,delhi,kolhapur,mumbai,pune
0,False,False,True,False
1,False,False,False,True
2,True,False,False,False
3,False,True,False,False


In [9]:
multiclass_feature=[('mumbai','pune'),
                    ('kolhapur','satara'),
                    ('mumbai','kolhapur'),
                    ('sangli','pune'),
                    ('mumbai','nashik'),
                   ('mumbai','pune'),]

In [10]:
one_hot_multi=MultiLabelBinarizer()

In [11]:
one_hot_multi.fit_transform(multiclass_feature)
# print(one_hot_multi.classes_)

array([[0, 1, 0, 1, 0, 0],
       [1, 0, 0, 0, 0, 1],
       [1, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 1, 0],
       [0, 1, 1, 0, 0, 0],
       [0, 1, 0, 1, 0, 0]])

In [12]:
# Imputing Missing Class Values
from sklearn.neighbors import KNeighborsClassifier

In [13]:
X=np.array([[0,2.10,1.45],
            [1,1.18,1.33],
            [0,1.22,1.27],
            [1,-0.21,-1.19]])

In [14]:
X_with_nan=np.array([[np.nan,0.97,1.31],
                     [np.nan,-0.67,-0.22]])

In [15]:
clf=KNeighborsClassifier(3,weights='distance')

In [16]:
trained_model=clf.fit(X[:,1:],X[:,0])

In [17]:
imputed_values=trained_model.predict(X_with_nan[:,1:])

In [18]:
X_with_imputed=np.hstack((imputed_values.reshape(-1,1),X_with_nan[:,1:]))

In [19]:
np.vstack((X_with_imputed,X))

array([[ 0.  ,  0.97,  1.31],
       [ 1.  , -0.67, -0.22],
       [ 0.  ,  2.1 ,  1.45],
       [ 1.  ,  1.18,  1.33],
       [ 0.  ,  1.22,  1.27],
       [ 1.  , -0.21, -1.19]])

In [20]:
from sklearn.impute import SimpleImputer

In [21]:
X_complete=np.vstack((X,X_with_nan))

In [22]:
imputer=SimpleImputer(strategy='most_frequent')


In [23]:
imputer.fit_transform(X_complete)

array([[ 0.  ,  2.1 ,  1.45],
       [ 1.  ,  1.18,  1.33],
       [ 0.  ,  1.22,  1.27],
       [ 1.  , -0.21, -1.19],
       [ 0.  ,  0.97,  1.31],
       [ 0.  , -0.67, -0.22]])